Repository ThugDev/PurrTunes, pull requests merged in 2024-09, with the labels that each got.

#10 sign-in / sign-out (+ change global state library)
  app/_/api/type.ts
  app/_/api/youtubeAPI.ts
  app/_/components/layout/authStatus.tsx
  app/_/components/layout/dialog.tsx
  app/_/components/layout/header.tsx
  app/_/components/search/searchModal.tsx
  app/_/hooks/useSearch.ts
  app/_/libs/jotai/dialog.ts
  app/_/libs/jotai/modal.ts
  app/_/libs/zustand/modal.ts
  app/_/libs/zustand/type.ts
  app/api/auth/[...nextauth]/route.ts
  app/layout.tsx
  app/sessionLayout.tsx
  app/sign-in/page.tsx
  middleware.ts
  next.config.mjs
  package-lock.json
  package.json
Labels: 🟢 feat

#11 Install & apply SWR
  app/_/hooks/useSearch.ts
  package-lock.json
  package.json
Labels: 🟢 feat

#12 Create Search Result Page
  app/_/api/youtubeAPI.ts
  app/_/components/albumCard.tsx
  app/_/components/layout/header.tsx
  app/_/components/type.ts
  app/_/hooks/useSearch.ts
  app/search/_components/searchBar.tsx
  app/search/_components/searchInput.tsx
  app/search/_components/searchModal.tsx
  app/search/_components/searchResult.tsx
  app/search/_components/suggestions.tsx
  app/search/_components/suggestionsList.tsx
  app/search/_components/type.ts
  app/search/page.tsx
  app/search/type.ts
  next.config.mjs
  package-lock.json
  package.json
Labels: 🟢 feat

#14 Publishing auth sign-in modal
  app/_/components/layout/authStatus.tsx
  app/_/components/layout/header.tsx
  app/_/constants/.gitkeep
  app/_/constants/authProviders.ts
  app/_/constants/type.ts
  app/_/hooks/type.ts
  app/_/hooks/useModalClose.ts
  app/_/libs/jotai/searchModal.ts
  app/_/libs/jotai/signInModal.ts
  app/search/_components/searchModal.tsx
  app/sign-in/page.tsx
  public/icon/.gitkeep
  public/icon/google.svg
  public/icon/kakao.svg
  tailwind.config.ts
Labels: 🟢 feat, 🎁 style

#16 fetch popular albums and change album css
  app/_/api/youtubeAPI.ts
  app/_/components/albumCard.tsx
  app/_/components/common/albumCard.tsx
  app/_/components/common/type.ts
  app/_/components/type.ts
  app/_/styles/color.ts
  app/_/utils/.gitkeep
  app/_/utils/length-helper.ts
  app/_components/mainAlbums.tsx
  app/search/_components/searchBar.tsx
  app/search/_components/searchModal.tsx
  app/search/_components/searchResult.tsx
  app/search/_components/type.ts
  app/search/page.tsx
  app/search/type.ts
  package-lock.json
Labels: 🟢 feat, 🎁 style

#17 Publish/member dialog
  app/_/components/layout/_components/authButton.tsx
  app/_/components/layout/_components/authButtons.tsx
  app/_/components/layout/_components/modalTitle.tsx
  app/_/components/layout/dialog.tsx
  app/_/components/layout/header.tsx
  app/_/components/layout/membersOnly/authStatus.tsx
  app/_/components/layout/membersOnly/dialog.tsx
  app/_/components/layout/membersOnly/oneList.tsx
  app/_/components/layout/membersOnly/type.ts
  app/_/constants/dialogList.ts
  app/_/constants/type.ts
  app/_components/mainAlbums.tsx
  app/sign-in/page.tsx
  next.config.mjs
Labels: 🎁 style, 💡 refactor
